# Generated by Django 4.2.7 on 2023-12-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('title', models.CharField(default='No album title', max_length=100)),
                ('query', models.CharField(default='No query', max_length=100)),
                ('image', models.CharField(default='No image', max_length=500)),
                ('albumId', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('external', models.CharField(default='No external URL', max_length=100)),
                ('uri', models.CharField(default='No URI', max_length=100)),
                ('mainArtist', models.CharField(default='No artist', max_length=600)),
                ('artists', models.CharField(default='No artists', max_length=500)),
                ('releaseDate', models.CharField(blank=True, default='No release date', max_length=20, null=True)),
                ('popularity', models.FloatField(default=0, max_length=11)),
                ('theType', models.CharField(default='No type', max_length=10)),
                ('artistId', models.CharField(default='None', max_length=500)),
                ('year', models.CharField(default='No release year', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('genres', models.CharField(default='No genres', max_length=500)),
                ('query', models.CharField(default='No query', max_length=100)),
                ('name', models.CharField(default='No name', max_length=500)),
                ('artistId', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('external', models.CharField(default='No external URL', max_length=500)),
                ('uri', models.CharField(default='No URI', max_length=500)),
                ('image', models.CharField(default='No image', max_length=500)),
                ('popularity', models.FloatField(default=0, max_length=501)),
                ('numOfFollowers', models.CharField(default='0', max_length=500)),
                ('songId', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('albumId', models.CharField(blank=True, default='None', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.CharField(default='No song title', max_length=100)),
                ('query', models.CharField(default='No query', max_length=100)),
                ('album', models.CharField(default='No album', max_length=100)),
                ('songId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('preview', models.CharField(blank=True, default='None', max_length=400, null=True)),
                ('external', models.CharField(default='No external URL', max_length=100)),
                ('uri', models.CharField(default='No URI', max_length=100)),
                ('duration', models.CharField(default='No duration', max_length=10)),
                ('mainArtist', models.CharField(default='No artist', max_length=100)),
                ('artists', models.CharField(default='No artists', max_length=100)),
                ('popularity', models.FloatField(default=0, max_length=101)),
                ('image', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('theType', models.CharField(default='No type', max_length=10)),
                ('albumId', models.CharField(default='None', max_length=100)),
                ('artistId', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=50)),
            ],
        ),
    ]
